#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pprint
pp = pprint.PrettyPrinter(indent=4)
import sys
from urlparse import urlparse
import socket
import json

class hostchecker:

    def __init__(self, url, domain, ip):
        self.url    = url
        self.domain = domain
        self.ip     = ip

    # URLからホスト名を切り出す
    def slice_hostoname(self):
        try：
            urlparse_obj = urlparse(self.url)
            return urlparse_obj.hostname
        except:
            return False

    # ドメインからIPアドレスを問い合わせる / 正引き
    def fowarod_lookup(self):
        try:
            return socket.gethostbyname(self.domain)
        except:
            return False

    # ipアドレスからドメインを問い合わせる / 逆引き
    def reverse_lookup(self):
	    try:
		    return socket.gethostbyaddr(self.ip)
    	except:
	    	return False
    
    # geoipで
    def geoip_lookup(self):
        try:
            return hoge
        except:
            return False

    def whois_lookup(self):
        try:
            return hoge
        except:
            return False
    
    def httpheader_lookup(self):
        try:
            return hoge
        except:
            return False


    def formatter_msg(self):
        try:
            return print("  {}\n".format(self.msg))
        except:
            return False

if __name__ == '__main__':
 
    args = sys.argv
    input_url = args[1]

    print("URL:")
    print("IPAddress:")
    print("ResolveHostName:")






