#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pprint
pp = pprint.PrettyPrinter(indent=4)
import sys
from urlparse import urlparse
import socket
from geoip import geolite2
import whois
#import pyasn
import urllib2


import json

class hostchecker:

    def __init__(self, url, output):
        self.url    = url
        self.output = output
        self.struct = {}

    def hostoname_lookup(self):

            # URLからホスト名を抽出
            #pp.pprint(self.url)   
            urlparse_obj = urlparse(self.url)
            self.hostname = urlparse_obj.hostname
            self.struct["hostname"] = self.hostname

            # ホスト名からIPアドレスを引く
            self.ipaddr = socket.gethostbyname(self.hostname)
            self.struct["ipaddr"] = self.ipaddr

            # IPアドレスからホスト名を引く
            self.resolve_hostname = socket.gethostbyaddr(self.ipaddr)
            self.struct["resolve_hostname"] = self.resolve_hostname

            # geoipで国情報を取得
            match = geolite2.lookup(self.ipaddr)
            geoip = {}
            geoip["county"] = match.country
            geoip["timezone"] = match.timezone
            geoip["continent"] = match.continent
            geoip["subdivisions"] = match.subdivisions
            #pp.pprint(geoip)
            self.struct["geoip"] = geoip

            # whois情報を取得
            w = whois.query("azurestone.net")
            #pp.pprint(w.__dict__)
            self.whois = w.__dict__
            self.struct["whois"] = self.whois
            
            # http headerを取得
            user_agent = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)'
            headers = {'User-Agent': user_agent}
            #req = urllib2.request.Request(url, data, headers)
            
            pp.pprint(self.struct)

if __name__ == '__main__':
 
    args = sys.argv
    input_url = args[1]    

    hc = hostchecker("http://www.azurestone.net/", "json")
    hc.hostoname_lookup()
    






