#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pprint
pp = pprint.PrettyPrinter(indent=4)
import sys
from urllib.parse import urlparse
import socket
import urllib.request
import geoip2.database
import os
import tarfile
import json

class hostchecker:

    def __init__(self, url, output):
        self.url    = url
        self.output = output
        self.struct = {}

    def full_lookup(self):

            # URLからホスト名を抽出
            #pp.pprint(self.url)   
            urlparse_obj = urlparse(self.url)
            self.hostname = urlparse_obj.hostname
            self.struct["hostname"] = self.hostname

            # ホスト名からIPアドレスを引く
            self.ipaddr = socket.gethostbyname(self.hostname)
            self.struct["ipaddr"] = self.ipaddr

            # IPアドレスからホスト名を引く
            self.resolve_hostname = socket.gethostbyaddr(self.ipaddr)
            self.struct["resolve_hostname"] = self.resolve_hostname

            # geoipデータベースの取得
            #   https://github.com/maxmind/GeoIP2-python#database-example
            #   http://dev.maxmind.com/geoip/geoip2/geolite2/
            geoip_database_url = "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz"
            if not os.path.exists("GeoLite2-City_20170704/GeoLite2-City.mmdb"):
                print("Download GetIP Datbase ...")
                urllib.request.urlretrieve(geoip_database_url, "GeoLite2-City_20170704.tar.gz")
                tf = tarfile.open("GeoLite2-City_20170704.tar.gz", "r")
                print("Expanding GetIP Database ...")
                tf.list()
                tf.extractall()
                tf.close

            #pp.pprint(self.ipaddr)
            reader = geoip2.database.Reader('GeoLite2-City_20170905/GeoLite2-City.mmdb', ['ja'])
            response = reader.city(self.ipaddr)

            geoip = {}
            #pp.pprint(response)
            geoip["county"] = response.country.iso_code
            geoip["county_name"] = response.country.name
            geoip["subdivisions"] = response.subdivisions.most_specific.iso_code
            geoip["subdivisions_name"] = response.subdivisions.most_specific.name
            geoip["cityname"] = response.city.name
            geoip["postal_code"] = response.postal.code
            geoip["location_latitude"] = response.location.latitude
            geoip["location_longitude"] = response.location.longitude
            #pp.pprint(geoip)
            self.struct["geoip"] = geoip
            
            #pp.pprint(self.struct)
            return self.struct

    """    
    URLからホスト名を抽出して、IPアドレスを引く
    引数にURLを渡す
    """
    def lookup_ipaddr(self, url):

        self.struct = {}
        self.url = url

        # URLからホスト名を抽出
        #pp.pprint(self.url) 
        urlparse_obj = urlparse(self.url)
        self.hostname = urlparse_obj.hostname
        self.struct["hostname"] = self.hostname

        # ホスト名からIPアドレスを引く
        self.ipaddr = socket.gethostbyname(self.hostname)
        self.struct["ipaddr"] = self.ipaddr

        return self.struct

    """
    IPアドレスからホスト名を引く
    """
    def lookup_hostname(self, ipaddr):

        self.struct = {}
        self.ipaddr = ipaddr
         
        self.resolve_hostname = socket.gethostbyaddr(self.ipaddr)
        self.struct["resolve_hostname"] = self.resolve_hostname

        return self.struct

    """
    IPアドレスからGeoIPデータベースを検索する
    """
    def lookup_geoip(self, ipaddr):

        self.struct = {}
        self.ipaddr = ipaddr

        """
        geoipデータベースの取得
            https://github.com/maxmind/GeoIP2-python#database-example
            http://dev.maxmind.com/geoip/geoip2/geolite2/
        """
        geoip_database_url = "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz"
        if not os.path.exists("GeoLite2-City_20170704/GeoLite2-City.mmdb"):
            print("Download GetIP Datbase ...")
            urllib.request.urlretrieve(geoip_database_url, "GeoLite2-City_20170704.tar.gz")
            tf = tarfile.open("GeoLite2-City_20170704.tar.gz", "r")
            print("Expanding GetIP Database ...")
            tf.list()
            tf.extractall()
            tf.close

        #pp.pprint(self.ipaddr)
        reader = geoip2.database.Reader('GeoLite2-City_20170704/GeoLite2-City.mmdb', ['ja'])
        response = reader.city(self.ipaddr)

        geoip = {}
        #pp.pprint(response)
        geoip["county"] = response.country.iso_code
        geoip["county_name"] = response.country.name
        geoip["subdivisions"] = response.subdivisions.most_specific.iso_code
        geoip["subdivisions_name"] = response.subdivisions.most_specific.name
        geoip["cityname"] = response.city.name
        geoip["postal_code"] = response.postal.code
        geoip["location_latitude"] = response.location.latitude
        geoip["location_longitude"] = response.location.longitude
        #pp.pprint(geoip)
        self.struct["geoip"] = geoip
            
        #pp.pprint(self.struct)
        return self.struct

    def output(self, data, format):

        self.data = data
        self.format = format

        if format -- 'json':
            print(json.dumps(self.data, ensure_ascii=False, indent=4, sort_keys=True, separators=(',', ': ')))
                

if __name__ == '__main__':
 
    args = sys.argv
    input_url = args[1]    

    hc = hostchecker(input_url, "json")
    struct_data = hc.full_lookup()
    print(json.dumps(struct_data, ensure_ascii=False, indent=4, sort_keys=True, separators=(',', ': ')))




